services:
db:
    container_name: mysql
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=GloriaMESSENG
    ports:
      - '3307:3307'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  spring_app:
    container_name: jenkins-pipeline
    image: gloria6056/jenkins-pipeline
    restart: on-failure
    build: .
    ports:
      - 9090:9090
    depends_on:
      - db
volumes:
  mysql:
    driver: local